import React from "react";
import { Provider } from "react-redux";
import 'bootstrap/dist/css/bootstrap.min.css';
import store from "./store";
import RootLayout from "./layout";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const App = ({ Component, pageProps }) => (
        <Provider store={store}>
            <RootLayout>
                <Component {...pageProps} />
            </RootLayout>
        </Provider>
)

export default App;