import React from "react";
import { Provider } from "react-redux";
import 'bootstrap/dist/css/bootstrap.min.css';
import { store, persistor } from "../app/store";
import RootLayout from "../app/layout";
import { PersistGate } from "redux-persist/integration/react";
import { Container, Spinner } from "react-bootstrap";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const Loading = () => (
    <Container className="h-100 w-100 d-flex justify-content-center align-items-center text-center">
        <p>Loading...</p>
        <Spinner />
    </Container>
)

const App = ({ Component, pageProps }) => (
    <Provider store={store}>
        <PersistGate loading={<Loading />} persistor={persistor}>
            <RootLayout>
                <Component {...pageProps} />
            </RootLayout>
        </PersistGate>
    </Provider>
)

export default App;